"""Level layouts and quiz content for Future Run (Worlds 1–4)."""

from future_run.constants import GROUND_ROW

# Correct index is 0=A, 1=B, 2=C
QUIZZES = {
    "career": {
        "id": "career",
        "title": "Career Confusion",
        "prompt": "What should you do when you're unsure what to do after graduation?",
        "choices": [
            "I'll figure it out later",
            "Research my options",
            "Whatever my friend is doing",
        ],
        "correct": 1,
        "points": 100,
        "fail": "Maybe your future will figure itself out. Spoiler: it probably won't.",
        "life_on_fail": -1,
        "reward": None,
    },
    "overload": {
        "id": "overload",
        "title": "Information Overload",
        "prompt": "You have a big assignment due, multiple things to do, and no idea where to start. What do you do?",
        "choices": [
            "Panic and scroll Instagram",
            "Break it into smaller tasks and start with one",
            "Wait until the night before",
        ],
        "correct": 1,
        "points": 100,
        "fail": "The deadline didn't disappear. Neither did the assignment.",
        "life_on_fail": -1,
        "reward": None,
    },
    "shortlist": {
        "id": "shortlist",
        "title": "University Shortlist",
        "prompt": "You need to pursue a Master's. How are you choosing your university?",
        "choices": [
            "This one is famous",
            "This is trending on Instagram",
            "Check which one actually fits me",
        ],
        "correct": 2,
        "points": 100,
        "fail": "Trending ≠ right for you. Your future isn't an Instagram trend.",
        "life_on_fail": -1,
        "reward": "right_fit",
        "financial": False,
    },
    "agent": {
        "id": "agent",
        "title": "Study Abroad Agent",
        "prompt": 'An agent says: "Bro, trust me. This university is PERFECT for you." What do you do?',
        "choices": [
            "Say less. I'm applying.",
            "Let me check the university fit first",
            "My cousin knows a guy",
        ],
        "correct": 1,
        "points": 200,
        "fail": "Bro trusted bro. Your future would like a second opinion.",
        "life_on_fail": -1,
        "reward": "right_fit",
        "financial": False,
    },
    "loan": {
        "id": "loan",
        "title": "Education Loan",
        "prompt": "You need funding for your Master's. What should you do?",
        "choices": [
            "Take the first loan offered",
            "Compare loan options",
            "Ask WhatsApp University",
        ],
        "correct": 1,
        "points": 250,
        "fail": "Congratulations, WhatsApp University has awarded you a PhD in bad advice.",
        "life_on_fail": -1,
        "reward": "money_boost",
        "financial": True,
    },
    "community": {
        "id": "community",
        "title": "Doubt Zone",
        "prompt": "You're stuck and don't know what to do. What's your best move?",
        "choices": [
            "Guess",
            "Ask random people on the internet",
            "Ask a community of students who have been through it",
        ],
        "correct": 2,
        "points": 100,
        "fail": "Random internet advice unlocked: absolutely nothing useful.",
        "life_on_fail": 0,
        "reward": "community",
        "financial": False,
    },
    "fomo": {
        "id": "fomo",
        "title": "FOMO Billboard",
        "prompt": 'A giant billboard says "EVERYONE IS DOING THIS COURSE!" What should you do?',
        "choices": [
            "Run through",
            "Check if it's right for you",
            "Follow everyone else",
        ],
        "correct": 1,
        "points": 150,
        "fail": "FOMO hit! Apparently everyone else is planning your career too.",
        "life_on_fail": -1,
        "reward": None,
        "financial": False,
    },
    "upskill": {
        "id": "upskill",
        "title": "Dream Job Locked",
        "prompt": "This job requires a skill you don't have. What do you do?",
        "choices": [
            "Ignore it",
            "Start learning the skill",
            "Put it on your CV anyway",
        ],
        "correct": 1,
        "points": 100,
        "fail": "Fake it till you make it? Not when the interview starts.",
        "life_on_fail": -1,
        "reward": "skill_boost",
        "financial": False,
    },
    "biggest": {
        "id": "biggest",
        "title": "The Biggest Decision",
        "prompt": "What gets you closer to your future?",
        "choices": [
            "Guessing",
            "Following everyone else",
            "Making informed decisions",
        ],
        "correct": 2,
        "points": 250,
        "fail": "Plot twist: your future isn't a multiple-choice guess.",
        "life_on_fail": 0,
        "reward": "future_ready",
        "financial": False,
    },
}


def _coins(pairs):
    gy = GROUND_ROW
    return [(c, gy - r if r < 20 else r) for c, r in pairs]


# Each level: cols, pits as (start_col, end_col), coins, books cols, phones,
# platforms (col, row, width), decor, pickups, triggers, sky tint optional.
LEVELS = [
    {
        "id": 1,
        "code": "1-1",
        "name": "FIGURE IT OUT",
        "subtitle": "College + Career Confusion",
        "cols": 96,
        "pits": [(20, 23)],
        "coins": [
            (6, 3), (7, 3), (8, 3), (9, 3), (10, 3),
            (11, 5), (12, 5), (13, 5),
            (38, 4), (39, 4), (40, 4), (41, 4), (42, 4),
            (56, 5), (57, 5), (58, 5), (59, 5),
        ],
        "books": [(16, "tall")],
        "phones": [
            (42, 4, 40, 52, 3.2),
            (46, 6, 41, 53, 4.0),
            (50, 3, 43, 54, 2.8),
        ],
        "platforms": [],
        "falling": [],
        "fomo_boards": [],
        "clouds": [(5, 3), (14, 2), (28, 3), (40, 1), (55, 3), (70, 2), (84, 2)],
        "decor": [
            ("bush", 3), ("board", 10), ("plant", 28), ("bench", 36),
            ("bike", 48), ("bush", 64), ("board", 78),
        ],
        "pickups": [("graddie", 62)],
        "triggers": [
            (32, "quiz", "career", 6),
            (72, "quiz", "overload", 6),
            (86, "goal", None, 8),
        ],
        "sky": "day",
        "backdrop": "world1",
    },
    {
        "id": 2,
        "code": "2-1",
        "name": "GO GLOBAL",
        "subtitle": "Study Abroad Decisions",
        "cols": 140,
        "pits": [(18, 21), (54, 57), (98, 101)],
        "coins": [
            (4, 3), (5, 3), (6, 3), (7, 3),
            (22, 5), (23, 5), (24, 5),
            (40, 3), (41, 4), (42, 5), (43, 4), (44, 3),
            (68, 4), (69, 4), (70, 4), (71, 4),
            (88, 5), (89, 5), (90, 5),
            (110, 3), (111, 3), (112, 3), (113, 3), (114, 3),
        ],
        "books": [(40, "newspaper"), (94, "money_trap")],
        "phones": [
            (30, 4, 28, 38, 3.6),
            (34, 6, 29, 40, 4.2),
            (72, 3, 70, 82, 3.4),
            (76, 5, 71, 84, 4.5),
            (78, 7, 72, 86, 3.0),
        ],
        "platforms": [
            (22, GROUND_ROW - 4, 4),
            (64, GROUND_ROW - 5, 5),
            (106, GROUND_ROW - 4, 4),
        ],
        "falling": [
            # Before 2nd quiz: one alarm clock left of false-info. After quiz: confusion clouds.
            (48, 2, 2.4),
            (84, 3, 2.8, "confusion_cloud"),
        ],
        "falling_sprite": "alarm_clock",
        "fomo_boards": [(118,)],
        "clouds": [
            (3, 2), (16, 3), (35, 1), (50, 3), (70, 2),
            (90, 3), (110, 2), (125, 1),
        ],
        "decor": [
            ("bush", 2), ("board", 8), ("plant", 26), ("bench", 44),
            ("bike", 60), ("bush", 80), ("plant", 102), ("board", 130),
        ],
        "pickups": [("graddie", 24)],
        "npcs": [("agent", 60)],
        "triggers": [
            (36, "quiz", "shortlist", 6),
            (60, "quiz", "agent", 6),
            (86, "quiz", "loan", 6),
            (108, "quiz", "community", 6),
            (120, "quiz", "fomo", 6),
            (132, "goal", None, 8),
        ],
        "sky": "dusk",
        "backdrop": "world2",
    },
    {
        "id": 3,
        "code": "3-1",
        "name": "LEVEL UP",
        "subtitle": "Skills + Career",
        "cols": 110,
        "pits": [(24, 27), (48, 51), (78, 81)],
        "coins": [
            (5, 3), (6, 3), (7, 3), (8, 4), (9, 5),
            (30, 4), (31, 4), (32, 4), (33, 4),
            (54, 5), (55, 5), (56, 5), (57, 5), (58, 5),
            (70, 3), (71, 4), (72, 5), (73, 4), (74, 3),
            (90, 4), (91, 4), (92, 4),
        ],
        "books": [(40, "short"), (66, "skill_barrier"), (84, "short")],
        "phones": [
            (34, 4, 32, 44, 4.0),
            (38, 6, 33, 46, 4.8),
            (58, 3, 56, 68, 3.8),
            (62, 5, 57, 70, 5.0),
            (64, 7, 58, 72, 3.5),
        ],
        "platforms": [
            (28, GROUND_ROW - 4, 5),
            (52, GROUND_ROW - 6, 4),
            (74, GROUND_ROW - 5, 5),
        ],
        "falling": [
            (20, 2, 3.0),
            (22, 5, 2.6),
            (46, 3, 3.4),
            (76, 2, 3.2),
            (88, 4, 2.9),
        ],
        "falling_sprite": "paper_stack",
        "fomo_boards": [],
        "clouds": [(4, 2), (20, 3), (40, 1), (60, 3), (80, 2), (95, 1)],
        "decor": [
            ("bush", 3), ("board", 12), ("bike", 28), ("bench", 50),
            ("plant", 72), ("bush", 96),
        ],
        "pickups": [("graddie", 44)],
        "triggers": [
            (36, "quiz", "upskill", 8),
            (98, "goal", None, 8),
        ],
        "sky": "city",
        "backdrop": "world3",
    },
    {
        "id": 4,
        "code": "4-1",
        "name": "FUTURE READY",
        "subtitle": "The Biggest Decision",
        "cols": 100,
        "pits": [(16, 18), (37, 39), (58, 60), (76, 78)],
        "coins": [
            (4, 3), (5, 3), (6, 3),
            (20, 5), (21, 5), (22, 5), (23, 5),
            (42, 4), (43, 5), (44, 6), (45, 5), (46, 4),
            (64, 3), (65, 3), (66, 3), (67, 3),
            (82, 5), (83, 5), (84, 5),
        ],
        "books": [(70, "false_info")],
        "phones": [
            (24, 4, 22, 32, 3.6),
            (48, 3, 46, 56, 3.4),
            (68, 4, 66, 74, 3.8),
            (72, 7, 67, 76, 3.0),
        ],
        "platforms": [
            (20, GROUND_ROW - 4, 4),
            (42, GROUND_ROW - 5, 5),
            (62, GROUND_ROW - 6, 4),
            (80, GROUND_ROW - 4, 4),
        ],
        "falling": [
            (34, 3, 3.1),
            (56, 5, 2.6),
            (74, 3, 2.9),
        ],
        "falling_sprite": "alarm_clock",
        "fomo_boards": [],
        "clouds": [(2, 2), (18, 3), (38, 1), (55, 3), (75, 2), (90, 1)],
        "decor": [
            ("bush", 2), ("plant", 10), ("board", 28), ("bench", 46),
            ("bike", 64), ("bush", 88),
        ],
        "pickups": [("graddie", 40)],
        "triggers": [
            (84, "quiz", "biggest", 8),
            (92, "goal", None, 8),
        ],
        "sky": "future",
        "backdrop": "world4",
    },
]
